Repository MemeLabs/Rustla2, pull requests merged in 2019-03, with the labels that each got.

#138 swapped old AT player for the new player
  src/components/StreamEmbed.jsx
Labels: frontend

#139 react@^16.8.4, react-dom@^16.8.4
  package-lock.json
  package.json
Labels: deps, frontend

#140 webpack-cli@^3.2.3
  package-lock.json
  package.json
Labels: deps, frontend

#143 webpack-subresource-integrity@^1.3.2
  package-lock.json
  package.json
Labels: deps, frontend, tools

#145 flow-bin@^0.95.1
  package-lock.json
  package.json
Labels: deps, frontend, tools

#147 @babel/*@^7.4.0, ^7.4.1
  package-lock.json
  package.json
Labels: deps, frontend, tools

#148 eslint@^5.15.3
  package-lock.json
  package.json
Labels: deps, frontend, tools
